### ISSUE TITLE
通道操作-开关

### ISSUE THREAD

**Issue by dvasdfva** [dgiot/dgiot_dashboard#103]
![image](https://user-images.githubusercontent.com/55369307/127954675-59c51c23-9f29-44f1-9dc2-96740220110d.png)
相较与现在之前的版本，在操作控制通道开启和关闭的界面显得有一些不合适。即开和关颜色都是黄色，之前开始绿色关是红色，这样可以方便我们更加直观的查看到通道状态。另外，由于TD通道和Instruct通道是公用的，随着通道越来越多造成一个在第一页一个在第4页的情况，所以重启通道这个过程变得非常繁琐。建议可以把存储和指令通道固定在顶部，这样可以方便我们重启。异或创建一个全开全关按钮方便操作。

**Comment by h7ml** [comment]
已收到建议，预计明天修复。
