### ISSUE TITLE
低代码开发

### ISSUE THREAD

**Issue by Keda-iot** [dgiot/dgiot_dashboard#76]
这几天看了部分你们代码。文档有提及到低代码开发，请问具体表现在哪里。

**Comment by yxc45678** [comment]
动态表单   https://tech.iotn2n.com/zh/product/dgiot/cloudoperation/
物模型       https://tech.iotn2n.com/zh/product/dgiot/device_cloud/product/
规则联动   https://tech.iotn2n.com/zh/product/dgiot/device_cloud/rules/rule-engine.html
字典管理   https://tech.iotn2n.com/zh/product/dgiot/device_cloud/dict/#%E5%AD%97%E5%85%B8%E7%AE%A1%E7%90%86

这是部分模块你可以看一下，都是低代码开发的。另外如果有问题可以继续提问
