### ISSUE TITLE
主界面视图

### ISSUE THREAD

**Issue by zxcnrt** [dgiot/dgiot_dashboard#80]
大佬这个随机界面也太不协调了，能不能改一些稳定的版本放上去啊。
![image](https://user-images.githubusercontent.com/55369012/127249939-56cb5adf-79c9-45c5-ab38-fb6c3872f40a.png)

**Comment by zxcnrt** [comment]
是logo的位置异常，显得不协调

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/127262986-dd969a79-3460-4444-a4a5-f137d5a89526.png)

logo 图片大小因为 250 * 63 该logo 为 266 * 95.29
