### ISSUE TITLE
实时视频解码与视频格式支持

### ISSUE THREAD

**Issue by zxcnrt** [dgiot/dgiot_dashboard#81]
![image](https://user-images.githubusercontent.com/55369012/127250742-2178a193-057e-422b-8979-294ff3400beb.png)
就是我想在视频播放这里加上我摄像机的实时流。但是视频播放的格式好像不支持，只有mp4格式支持。是因为浏览器问题还是没有开发完善。另外这个视频延时在10s以内吗

**Comment by h7ml** [comment]
目前只支持mp4和flv格式
